### ISSUE TITLE
Bug:  Condition will not be executed

### ISSUE THREAD

**Issue by huwentao1** [aave/protocol-v2#8]
https://github.com/aave/protocol-v2/blob/3782bfda1a9d0c9fa4c1bd26e69f1f3b3eed88ce/contracts/protocol/libraries/logic/ValidationLogic.sol#L200

No value is assigned to rateMode before using rateMode, which means
rateMode == 0, so I think this condition may never be executed

**Comment by The-3D** [comment]
Hello, thanks for finding this. The issue was found during the last audit by sigmaPrime and fixed accordingly immediately after the mainnet launch. https://github.com/aave/protocol-v2/blob/master/audits/SigmaPrime-aave-v2-01-2021.pdf. You can see here https://github.com/aave/protocol-v2/blob/9b509eadbb85352b04d3b86994ebf7c36ffe6e8a/contracts/protocol/libraries/logic/ValidationLogic.sol#L193 and in the implementation of the mainnet contracts.
Closing
